import { format, startOfMonth, endOfMonth, eachDayOfInterval, isSameDay } from 'date-fns';
import { Expense, ExpenseCategory, MonthlyReport } from '../types';

export const formatCurrency = (amount: number, currency: string = 'PKR'): string => {
  return `${currency} ${amount.toLocaleString('en-PK', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
};

export const formatDate = (date: string): string => {
  return format(new Date(date), 'MMM dd, yyyy');
};

export const formatDateShort = (date: string): string => {
  return format(new Date(date), 'MMM dd');
};

export const getMonthLabel = (year: number, month: number): string => {
  return format(new Date(year, month, 1), 'MMMM yyyy');
};

export const generateMonthlyReport = (
  expenses: Expense[],
  year: number,
  month: number
): MonthlyReport => {
  const monthExpenses = expenses?.filter((e) => {
    const d = new Date(e.date);
    return d.getFullYear() === year && d.getMonth() === month;
  }) ?? [];

  const totalExpense = monthExpenses?.reduce((sum, e) => sum + e.amount, 0) ?? 0;

  const categoryBreakdown = {} as Record<ExpenseCategory, number>;
  monthExpenses?.forEach((e) => {
    categoryBreakdown[e.category] = (categoryBreakdown[e.category] || 0) + e.amount;
  });

  return {
    month: `${year}-${String(month + 1).padStart(2, '0')}`,
    totalExpense,
    expenses: monthExpenses,
    categoryBreakdown,
  };
};

export const getDailyTotals = (
  expenses: Expense[],
  year: number,
  month: number
): { date: string; total: number }[] => {
  const start = startOfMonth(new Date(year, month, 1));
  const end = endOfMonth(new Date(year, month, 1));
  const days = eachDayOfInterval({ start, end });

  return days?.map((day) => {
    const dayExpenses = expenses?.filter((e) => isSameDay(new Date(e.date), day)) ?? [];
    const total = dayExpenses?.reduce((sum, e) => sum + e.amount, 0) ?? 0;
    return { date: format(day, 'dd'), total };
  });
};

export const generateEmailBody = (
  report: MonthlyReport,
  currency: string
): { subject: string; body: string } => {
  const monthLabel = format(
    new Date(parseInt(report.month.split('-')[0]), parseInt(report.month.split('-')[1]) - 1, 1),
    'MMMM yyyy'
  );

  const categoryLines = Object.entries(report.categoryBreakdown)
    ?.sort(([, a], [, b]) => b - a)
    ?.map(
      ([cat, amount]) =>
        `  • ${cat.charAt(0).toUpperCase() + cat.slice(1)}: ${formatCurrency(amount, currency)}`
    )
    ?.join('\n');

  const topExpenses = [...(report.expenses ?? [])]
    ?.sort((a, b) => b.amount - a.amount)
    ?.slice(0, 5)
    ?.map((e) => `  • ${e.title}: ${formatCurrency(e.amount, currency)} (${formatDate(e.date)})`)
    ?.join('\n');

  const subject = `💰 Expense Report — ${monthLabel}`;

  const body = `
══════════════════════════════════════
       MONTHLY EXPENSE REPORT
          ${monthLabel}
══════════════════════════════════════

TOTAL SPENT: ${formatCurrency(report.totalExpense, currency)}
TRANSACTIONS: ${report.expenses.length}

──────────────────────────────────────
📊 CATEGORY BREAKDOWN
──────────────────────────────────────
${categoryLines}

──────────────────────────────────────
🔝 TOP 5 EXPENSES
──────────────────────────────────────
${topExpenses}

──────────────────────────────────────

This report was generated by Expense Tracker.
  `.trim();

  return { subject, body };
};
